#pragma once

struct DebugSettings {
	int CONSOLE;
	int TEST;
	int CAPTEUR_GAUCHE_SAFE;
	int CAPTEUR_GAUCHE_DANGER;
	int CAPTEUR_CENTRE_SAFE;
	int CAPTEUR_CENTRE_DANGER;
	int CAPTEUR_DROIT_SAFE;
	int CAPTEUR_DROIT_DANGER;
	int BALAYAGE;
	int LUM_AMBIANTE;
	int LUM_DIRECTIONNELLE;
	int LUM_SPOT;
	int COLLISION;
	int VISUALS;
	int LOG;
};
