#pragma once

struct DebugSettings {
	int CONSOLE,
		TEST,
		CAPTEUR_GAUCHE_SAFE,
		CAPTEUR_GAUCHE_DANGER,
		CAPTEUR_CENTRE_SAFE,
		CAPTEUR_CENTRE_DANGER,
		CAPTEUR_DROIT_SAFE,
		CAPTEUR_DROIT_DANGER,
		BALAYAGE,
		LUM_AMBIANTE,
		LUM_DIRECTIONNELLE,
		LUM_SPOT,
		COLLISION,
		VISUALS,
		LOG;
};
