#pragma once

#include "DeleteTool.h"
#include "DuplicateTool.h"
#include "RotateTool.h"
#include "ScaleTool.h"
#include "TranslateTool.h"
#include "PositionTool.h"
#include "CenterTool.h"
#include "ValidCheckTool.h"
#include "InvalidTool.h"
#include "AngleTool.h"
#include "ValidcheckTool.h"
#include "InvalidTool.h"
#include "SetScaleTool.h"
#include "SelectTool.h"
#include "GetDataTool.h"